[project]
name = "autolaudonccp"
version = "0.1.0"
requires-python = ">=3.10,<3.13"

dependencies = [
  "streamlit",
  "pandas",
  "google-auth",
  "google-auth-oauthlib",
  "google-auth-httplib2",
  "google-api-python-client",
  "gspread"
]
